spring:
  application:
    name: kill
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 721000
    url: jdbc:mysql://localhost:3306/kill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    type: com.zaxxer.hikari.HikariDataSource

  rabbitmq:
    host: 192.168.108.127
    port: 5672
    username: guest
    password: guest

  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
    url: redis://localhost:6379
    database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  base-packages:
    - com.tang.kill.domain
    - com.tang.kill.dto
  configuration:
    map-underscore-to-camel-case: true